"""绘图默认值；在此统一修改颜色、线型和图例。"""

DEFAULT_3D_LINESTYLES = [
    "-",
    (0, (1, 10)),
    (0, (5, 10)),
    "-.",
    "--",
    ":",
    (0, (3, 10, 1, 10, 1, 10)),
    (5, (10, 3)),
    (0, (5, 5)),
    (0, (5, 1)),
]

UI_3D_COLORS = [
    "red",
    "blue",
    "green",
    "chocolate",
    "cyan",
    "yellow",
    "magenta",
    "purple",
    "orange",
    "gold",
    "brown",
    "pink",
    "darkgoldenrod",
    "darkcyan",
    "indigo",
    "olivedrab",
    "teal",
    "navy",
    "firebrick",
    "darkgreen",
    "cadetblue",
    "black",
    "aliceblue",
    "aquamarine",
    "azure",
    "coral",
]

LEGEND_DEFAULTS = dict(
    ncol=1,
    loc="best",
    borderpad=0.2,
    labelspacing=0.2,
    handlelength=1.5,
    handletextpad=0.2,
    columnspacing=0.3,
    fontsize=14,
)

DETAIL_LEGEND_DEFAULTS = dict(LEGEND_DEFAULTS, ncol=1, loc="图外右侧")

LOCATIONS = dict(
    best=0,
    northeast=1,
    northwest=2,
    southwest=3,
    southeast=4,
    east=7,
    west=6,
    south=8,
    north=9,
    center=10,
)

MPL_LOCATIONS = [
    "best",
    "upper right",
    "upper left",
    "lower left",
    "lower right",
    "right",
    "center left",
    "center right",
    "lower center",
    "upper center",
    "center",
    "图外右侧",
    "outside right",
]

DEFAULT_LINESTYLES = [
    "solid",
    "dashed",
    "dotted",
    "dashdot",
    (0, (1, 10)),
    (0, (5, 10)),
    (0, (3, 10, 1, 10, 1, 10)),
    (5, (10, 3)),
    (0, (5, 5)),
    (0, (5, 1)),
] * 2

DEFAULT_LINEWIDTHS = [1.5] * 20

DEFAULT_MARKERS = [
    "o",
    "s",
    "*",
    "P",
    "X",
    "D",
    "p",
    "x",
    "8",
    "2",
    "H",
    "+",
    "|",
    "<",
    ">",
    "^",
    "v",
    "d",
    None,
    "3",
]

DEFAULT_MARKERSIZES = [5.0] * 20

DEFAULT_COLORS = [
    "navy",
    "teal",
    "brown",
    "purple",
    "olivedrab",
    "orangered",
    "g",
    "r",
    "c",
    "m",
    "y",
    "k",
    "dodgerblue",
    "forestgreen",
    "b",
    "mediumvioletred",
    "goldenrod",
    "crimson",
    "gray",
]

DEFAULT_FILL_COLORS = [
    "#ffffff",
    "#E6E6E6",
    "#DCDCDC",
    "#D2D2D2",
    "#C8C8C8",
    "#C3C3C3",
    "#BEBEBE",
    "#B9B9B9",
    "#B4B4B4",
    "#AFAFAF",
    "#AAAAAA",
    "#A5A5A5",
    "#A0A0A0",
    "#9B9B9B",
    "#969696",
    "#919191",
    "#8C8C8C",
    "#878787",
    "#828282",
    "#7D7D7D",
    "#787878",
    "#6E6E6E",
    "#646464",
    "#646464",
    "#5F5F5F",
    "#5A5A5A",
    "#5A5A5A",
    "#565656",
    "#525252",
    "#4E4E4E",
    "#4A4A4A",
    "#464646",
    "#424242",
    "#3E3E3E",
    "#3A3A64",
]

DEFAULT_PATTERNS = [
    None,
    "--",
    "xx",
    "||",
    "..",
    "oo",
    "++",
    "**",
    "\\\\\\\\",
    "////",
    "-",
    "x",
    "|",
    ".",
    "o",
    "+",
    "*",
    "\\\\",
    "//",
    "---",
    "xxx",
    "|||",
    "...",
    "ooo",
    "+++",
    "***",
    "\\\\\\\\\\\\",
    "//////",
]

DEFAULT_3D_COLORS = [
    "b",
    "g",
    "r",
    "y",
    "m",
    "c",
    "lime",
    "lightcoral",
    "orange",
    "violet",
]
